products = [
  {
    '_id': '1',
    'name': 'johnnie-walker-black',
    'image': '/images/johnnie-walker-black-.jpg',
    'description':
      'Johnnie Walker Black Label is one of lifes true icons. A masterful blend of single malt and grain whiskies from across Scotland, aged for at least 12 years.',
    'brand': 'Johnnie Walker',
    'category': 'Alcohol',
    'price': 2400,
    'countInStock': 0,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'bikespare',
    'image': '/images/bikespare.jpg',
    'description':
      'Find here Bike Spare Parts, Motorcycle Parts',
    'brand': 'Bike',
    'category': 'sPare Part',
    'price': 599.99,
    'countInStock': 7,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': '3',
    'name': 'Gas',
    'image': '/images/gas.jpg',
    'description':
      'Pro gas',
    'brand': 'Sony',
    'category': 'Electronics',
    'price': 399.99,
    'countInStock': 11,
    'rating': 5,
    'numReviews': 12,
  },
    {
    '_id': '4',
    'name': 'miraa',
    'image': '/images/miraa.jpg',
    'description':
      'miraa',
    'brand': 'Miraa',
    'category': 'Miraa',
    'price': 209.99,
    'countInStock': 5,
    'rating': 3,
    'numReviews': 12,
  },
   {
    '_id': '5',
    'name': 'johnnie-walker-black',
    'image': '/images/johnnie-walker-black-.jpg',
    'description':
      'Johnnie Walker Black Label is one of lifes true icons. A masterful blend of single malt and grain whiskies from across Scotland, aged for at least 12 years.',
    'brand': 'Johnnie Walker',
    'category': 'Alcohol',
    'price': 2400,
    'countInStock': 0,
    'rating': 4.5,
    'numReviews': 12,
  },
 {
    '_id': '6',
    'name': 'johnnie-walker-black',
    'image': '/images/johnnie-walker-black-.jpg',
    'description':
      'Johnnie Walker Black Label is one of lifes true icons. A masterful blend of single malt and grain whiskies from across Scotland, aged for at least 12 years.',
    'brand': 'Johnnie Walker',
    'category': 'Alcohol',
    'price': 2400,
    'countInStock': 0,
    'rating': 4.5,
    'numReviews': 12,
  },
]